spring.application.name=Air Logic API
# H2 em modo arquivo
spring.datasource.url=jdbc:mysql://localhost:3306/airlogic_mobile?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=airlogic_mobile_adm
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update


server.port=8080

security.jwt.secret=f19910d59dd90ba8005ba376855d1bbc2de58b4fab4a7e37a6cc6bd5c1a69ba5
security.jwt.expiration=3600000