spring.application.name=Air Logic API
# H2 em modo arquivo
spring.datasource.url=jdbc:h2:file:./data/readings
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

server.port=8080

security.jwt.secret=f19910d59dd90ba8005ba376855d1bbc2de58b4fab4a7e37a6cc6bd5c1a69ba5
security.jwt.expiration=3600000